package top.wkbin.tianxuan.ui.settings.search

import top.wkbin.tianxuan.ui.components.RuntimeIconName

/**
 * 天玄全局功能与细粒度设置选项索引仓库
 * 全面深层收录天玄全系统的每一个子功能、具体配置项、开关与参数，支持多维加权检索与一键直达
 */
object SettingsSearchRegistry {

    /**
     * 热门快捷搜索推荐标签
     */
    val popularTags: List<String> = listOf(
        "模型档案",
        "本地 LLM",
        "思考流翻译",
        "SSH 服务",
        "存储挂载",
        "终端定制",
        "主题外观",
        "电池白名单",
        "幽灵进程",
        "Android SDK",
        "APK 签名",
        "MCP 协议",
        "工作流",
        "特权模式",
        "Web 协作台",
    )

    /**
     * 全局功能及深度子功能全量清单（覆盖所有一级、二级、三级功能及具体参数项）
     */
    val allItems: List<SettingsSearchItem> = listOf(
        // ==================== 1. 智能体与 AI 模型生态 ====================
        SettingsSearchItem(
            id = "agent_model_profiles",
            title = "模型档案管理",
            subtitle = "统一配置 OpenAI、DeepSeek、Claude、Gemini 等 API Key 与模型列表",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_PROFILES,
            icon = RuntimeIconName.Model,
            keywords = listOf("openai", "deepseek", "claude", "gemini", "qwen", "api", "key", "token", "端点", "密钥", "模型", "moxing", "miyao"),
            badge = "核心",
            breadcrumb = "智能体与 AI 模型 > 模型档案管理",
        ),
        SettingsSearchItem(
            id = "agent_model_create",
            title = "新建模型档案",
            subtitle = "添加新的大模型服务商配置与自定义推理参数",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_EDITOR_NEW,
            icon = RuntimeIconName.Plus,
            keywords = listOf("add", "new", "model", "新建", "添加", "自定义模型", "xinjian"),
            breadcrumb = "智能体与 AI 模型 > 模型档案 > 新建",
        ),
        SettingsSearchItem(
            id = "agent_model_apikey",
            title = "API Key 密钥与自定义 Base URL 端点",
            subtitle = "配置模型调用密钥、代理转发端点及反向代理 URL",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_PROFILES,
            icon = RuntimeIconName.Key,
            keywords = listOf("apikey", "api key", "base url", "endpoint", "url", "端点", "密钥", "代理端点", "miyao", "duandian"),
            breadcrumb = "智能体与 AI 模型 > 模型档案 > 密钥与端点",
        ),
        SettingsSearchItem(
            id = "agent_model_temp",
            title = "模型采样温度 (Temperature) 与 Top P",
            subtitle = "调节大模型生成的发散程度与确定性采样概率",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_PROFILES,
            icon = RuntimeIconName.Tune,
            keywords = listOf("temperature", "top_p", "top p", "温度", "采样", "随机度", "wendu", "caiyang"),
            breadcrumb = "智能体与 AI 模型 > 模型档案 > 推理参数",
        ),
        SettingsSearchItem(
            id = "agent_model_context_window",
            title = "上下文窗口 (Context Window) 与最大输出",
            subtitle = "设置模型的最大上下文 Token 上限与单次回复 Max Tokens",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_PROFILES,
            icon = RuntimeIconName.Speed,
            keywords = listOf("context window", "max tokens", "tokens", "token", "上下文窗口", "输出长度", "peie"),
            breadcrumb = "智能体与 AI 模型 > 模型档案 > Token 配额",
        ),
        SettingsSearchItem(
            id = "agent_model_vision",
            title = "视觉理解与图片输入支持 (Vision)",
            subtitle = "为模型启用图片编码直传与多模态视觉识别支持",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_PROFILES,
            icon = RuntimeIconName.Image,
            keywords = listOf("vision", "image", "multimodal", "视觉", "图片", "多模态", "tupian", "shijue"),
            breadcrumb = "智能体与 AI 模型 > 模型档案 > 多模态能力",
        ),
        SettingsSearchItem(
            id = "agent_model_reasoning",
            title = "深度思考标签 (Thinking / Reasoning Effort)",
            subtitle = "支持 DeepSeek R1、OpenAI o1/o3-mini 的 reasoning 思考模式",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MODEL_PROFILES,
            icon = RuntimeIconName.Brain,
            keywords = listOf("thinking", "reasoning", "r1", "o1", "o3", "深度思考", "思考标签", "推理努力", "shendusikao"),
            breadcrumb = "智能体与 AI 模型 > 模型档案 > 深度思考",
        ),
        SettingsSearchItem(
            id = "agent_local_llm",
            title = "本地 LLM 离线推理 (llama.cpp)",
            subtitle = "导入或下载 GGUF 模型，在 ARM64 设备端离线推理",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.LOCAL_LLM,
            icon = RuntimeIconName.Cpu,
            keywords = listOf("llama", "llm", "gguf", "端侧", "离线", "本地大模型", "bendi", "lixian", "qwen", "deepseek-r1"),
            badge = "端侧",
            breadcrumb = "智能体与 AI 模型 > 本地 LLM",
        ),
        SettingsSearchItem(
            id = "agent_local_gguf_import",
            title = "GGUF 本地量化模型文件导入",
            subtitle = "从手机存储导入 Q4_K_M、Q8_0 等格式的 GGUF 离线模型",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.LOCAL_LLM,
            icon = RuntimeIconName.FolderDownload,
            keywords = listOf("gguf", "q4_k_m", "q8_0", "模型文件", "导入模型", "daorumoxing"),
            breadcrumb = "智能体与 AI 模型 > 本地 LLM > GGUF 导入",
        ),
        SettingsSearchItem(
            id = "agent_local_threads",
            title = "本地推理 CPU 线程数与上下文容量",
            subtitle = "微调 llama.cpp 的 CPU 推理线程数与分配的上下文内存",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.LOCAL_LLM,
            icon = RuntimeIconName.Tune,
            keywords = listOf("threads", "cpu", "context size", "线程数", "离线性能", "xianchenshu"),
            breadcrumb = "智能体与 AI 模型 > 本地 LLM > 性能设置",
        ),
        SettingsSearchItem(
            id = "agent_quick_phrases",
            title = "快捷短语与常用指令",
            subtitle = "自定义智枢空白页快捷开始卡片与高频提示词模板",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.QUICK_PHRASES,
            icon = RuntimeIconName.Chat,
            keywords = listOf("prompt", "phrase", "提示词", "快捷短语", "常用指令", "模板", "kuaijie", "tishici"),
            breadcrumb = "智能体与 AI 模型 > 快捷短语",
        ),
        SettingsSearchItem(
            id = "agent_stats",
            title = "数据统计与用量看板",
            subtitle = "查看 Token 消耗、活跃度热力图、模型与话题排行",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.STATS,
            icon = RuntimeIconName.Speed,
            keywords = listOf("token", "stats", "usage", "用量", "统计", "热力图", "消耗", "费用", "tongji"),
            breadcrumb = "智能体与 AI 模型 > 数据统计",
        ),
        SettingsSearchItem(
            id = "agent_tool_center",
            title = "插件与底层工具中心",
            subtitle = "安装 llama.cpp、QEMU、Python、Node 等底层沙箱开发环境",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.TOOL_CENTER,
            icon = RuntimeIconName.Wrench,
            keywords = listOf("tools", "plugin", "qemu", "python", "node", "工具", "插件", "安装", "gongju", "chajian"),
            badge = "生态",
            breadcrumb = "智能体与 AI 模型 > 工具中心",
        ),
        SettingsSearchItem(
            id = "agent_cc_switch",
            title = "智能体中枢 (CC-Switch)",
            subtitle = "统一管理 Claude Code、OpenClaw、Hermes 版本与模型多源热切",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.CC_SWITCH,
            icon = RuntimeIconName.Sparkles,
            keywords = listOf("claude code", "openclaw", "hermes", "cc-switch", "切换", "中枢", "多源", "zhinengti"),
            breadcrumb = "智能体与 AI 模型 > CC-Switch",
        ),
        SettingsSearchItem(
            id = "agent_thinking_display",
            title = "思考流显示与折叠控制",
            subtitle = "控制 DeepSeek 等思考流模型的推理思维链是否默认展开",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Brain,
            keywords = listOf("thinking", "expand", "思考流", "折叠", "展开", "思维链", "sikaoliu"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 思考流",
        ),
        SettingsSearchItem(
            id = "agent_thinking_translate",
            title = "思考流自动中英文翻译",
            subtitle = "自动将外语思考流翻译为简体中文，降低阅读理解门槛",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Globe,
            keywords = listOf("translate", "translation", "翻译", "思考流翻译", "中文", "zidongfanyi"),
            badge = "实用",
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 自动翻译",
        ),
        SettingsSearchItem(
            id = "agent_system_prompt",
            title = "自定义全局系统提示词 (System Prompt)",
            subtitle = "设定 AI Agent 的预设人设、能力偏好与沙箱行为准则",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Prompt,
            keywords = listOf("system prompt", "prompt", "系统提示词", "人设", "自定义指令", "xitongtishici"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 系统提示词",
        ),
        SettingsSearchItem(
            id = "agent_compaction",
            title = "上下文自动压缩与裁剪 (Compaction)",
            subtitle = "长对话超出预设阈值时自动摘要历史上下文，防止爆 Token",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Compress,
            keywords = listOf("compaction", "compress", "summary", "上下文压缩", "裁剪", "摘要", "shangxiawen"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 上下文压缩",
        ),
        SettingsSearchItem(
            id = "agent_tool_rounds",
            title = "工具调用单轮与最大轮数限制",
            subtitle = "防止智能体死循环执行，设置单轮与全局 Tool 调用轮数上限",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Tune,
            keywords = listOf("rounds", "tool limit", "轮数", "调用限制", "循环防止", "lunshu"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 轮数限制",
        ),
        SettingsSearchItem(
            id = "agent_failures_circuit",
            title = "连续失败熔断上限 (Max Failures)",
            subtitle = "连续工具调用报错达到阈值时自动熔断并向用户请示",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Alert,
            keywords = listOf("failure", "circuit", "熔断", "连续失败", "容错", "rongduan"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 容错熔断",
        ),
        SettingsSearchItem(
            id = "agent_cmd_timeout",
            title = "PRoot 前台命令执行超时时间",
            subtitle = "设置前台命令的默认超时时间 (1~60分钟)，防止命令死锁",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Speed,
            keywords = listOf("timeout", "command timeout", "超时", "命令超时", "chaoshi"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 命令超时",
        ),
        SettingsSearchItem(
            id = "agent_approval_mode",
            title = "操作审批模式 (Approval Mode)",
            subtitle = "配置高危 Shell 命令与文件修改是否需要用户弹窗确认",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_EXECUTION,
            icon = RuntimeIconName.Shield,
            keywords = listOf("approval", "confirm", "审批", "确认", "危险操作", "shenpi"),
            breadcrumb = "智能体与 AI 模型 > Agent 执行参数 > 操作审批",
        ),
        SettingsSearchItem(
            id = "agent_subagents",
            title = "子智能体角色调度",
            subtitle = "配置自动委派策略与可用专业子智能体角色",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_SUBAGENTS,
            icon = RuntimeIconName.Bot,
            keywords = listOf("subagent", "子智能体", "委派", "分工", "角色", "多智能体", "zizhinengeti"),
            breadcrumb = "智能体与 AI 模型 > 子智能体管理",
        ),
        SettingsSearchItem(
            id = "agent_subagent_roles",
            title = "架构师与调试专家角色管理",
            subtitle = "管理 Architect、Developer、Reviewer 等内置与自定义角色",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_SUBAGENTS,
            icon = RuntimeIconName.Admin,
            keywords = listOf("architect", "developer", "reviewer", "debugger", "架构师", "调试专家", "角色"),
            breadcrumb = "智能体与 AI 模型 > 子智能体 > 角色定义",
        ),
        SettingsSearchItem(
            id = "agent_skills",
            title = "Skills 技能库与提示词扩展",
            subtitle = "管理 Skill 提示词、自动化脚本包与运行时能力扩展",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_SKILLS,
            icon = RuntimeIconName.Sparkles,
            keywords = listOf("skills", "skill", "技能", "脚本", "技能包", "jineng"),
            breadcrumb = "智能体与 AI 模型 > Skills 技能",
        ),
        SettingsSearchItem(
            id = "agent_skill_import",
            title = "导入与导出自定义 Skill 包",
            subtitle = "导入包含 SKILL.md 与脚本的本地目录或压缩包",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.AGENT_SKILLS,
            icon = RuntimeIconName.FolderDownload,
            keywords = listOf("skill import", "export", "导入技能", "导出技能", "daorujineng"),
            breadcrumb = "智能体与 AI 模型 > Skills 技能 > 导入导出",
        ),
        SettingsSearchItem(
            id = "agent_mcp",
            title = "MCP 协议生态与服务",
            subtitle = "管理 SQLite、Git、Fetch 等 Model Context Protocol 协议服务",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MCP_SETTINGS,
            icon = RuntimeIconName.Network,
            keywords = listOf("mcp", "model context protocol", "server", "sqlite", "git", "fetch", "xieyi"),
            breadcrumb = "智能体与 AI 模型 > MCP 协议生态",
        ),
        SettingsSearchItem(
            id = "agent_mcp_builtin_servers",
            title = "内置 SQLite / Git / Fetch MCP Server",
            subtitle = "管理沙箱内内置的轻量化数据与网络请求 MCP 服务端",
            category = SettingsSearchCategory.AGENT,
            target = SettingsSearchTarget.MCP_SETTINGS,
            icon = RuntimeIconName.Server,
            keywords = listOf("sqlite", "git", "fetch", "filesystem", "内置服务", "mcp server"),
            breadcrumb = "智能体与 AI 模型 > MCP 协议 > 内置服务",
        ),

        // ==================== 2. Linux 容器沙箱与存储 ====================
        SettingsSearchItem(
            id = "linux_distro",
            title = "Linux 发行版管理",
            subtitle = "多沙箱并存、镜像拉取 (Ubuntu/Debian/Arch/Alpine) 与主系统切换",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.DISTRO_MANAGEMENT,
            icon = RuntimeIconName.Server,
            keywords = listOf("distro", "rootfs", "ubuntu", "debian", "arch", "alpine", "kali", "fedora", "发行版", "镜像", "沙箱", "faxingban", "jingxiang"),
            badge = "容器",
            breadcrumb = "Linux 容器与存储 > 发行版管理",
        ),
        SettingsSearchItem(
            id = "linux_distro_ubuntu",
            title = "Ubuntu 22.04 / 24.04 沙箱系统",
            subtitle = "最常用 Linux 容器，生态完善，适配各类开发工具链",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.DISTRO_MANAGEMENT,
            icon = RuntimeIconName.Ubuntu,
            keywords = listOf("ubuntu", "apt", "jammy", "noble", "乌班图", "wubantu"),
            breadcrumb = "Linux 容器与存储 > 发行版管理 > Ubuntu",
        ),
        SettingsSearchItem(
            id = "linux_distro_debian",
            title = "Debian 12 Bookworm 轻量沙箱",
            subtitle = "资源占用极小，极低内存运行稳定版 Linux 环境",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.DISTRO_MANAGEMENT,
            icon = RuntimeIconName.Debian,
            keywords = listOf("debian", "bookworm", "apt", "德比安", "deb"),
            breadcrumb = "Linux 容器与存储 > 发行版管理 > Debian",
        ),
        SettingsSearchItem(
            id = "linux_distro_arch",
            title = "Arch Linux 滚动更新沙箱",
            subtitle = "Pacman 软件包仓库，极速获取最新编译器与工具链",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.DISTRO_MANAGEMENT,
            icon = RuntimeIconName.Arch,
            keywords = listOf("arch", "pacman", "aur", "滚动更新", "archlinux"),
            breadcrumb = "Linux 容器与存储 > 发行版管理 > Arch Linux",
        ),
        SettingsSearchItem(
            id = "linux_distro_alpine",
            title = "Alpine Linux 极简微容器",
            subtitle = "基于 musl libc 的轻量发行版，镜像仅数兆，启动极快",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.DISTRO_MANAGEMENT,
            icon = RuntimeIconName.Alpine,
            keywords = listOf("alpine", "apk", "musl", "极简", "小巧"),
            breadcrumb = "Linux 容器与存储 > 发行版管理 > Alpine Linux",
        ),
        SettingsSearchItem(
            id = "linux_distro_custom_tar",
            title = "导入自定义 RootFS 镜像压缩包 (tar.xz/tar.gz)",
            subtitle = "从手机本地导入已备份或自定义定制的 Linux 根文件系统",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.DISTRO_MANAGEMENT,
            icon = RuntimeIconName.FolderDownload,
            keywords = listOf("tar.xz", "tar.gz", "rootfs", "导入镜像", "自定义系统", "daorujingxiang"),
            breadcrumb = "Linux 容器与存储 > 发行版管理 > 导入自定义镜像",
        ),
        SettingsSearchItem(
            id = "linux_storage_usage",
            title = "存储管理与空间分析",
            subtitle = "按 Linux 沙箱、插件工具、项目工作区与 Skills 分析存储占用",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.STORAGE_USAGE,
            icon = RuntimeIconName.Storage,
            keywords = listOf("storage", "disk", "clean", "存储", "磁盘", "空间", "清理", "占用", "cunchu", "kongjian"),
            breadcrumb = "Linux 容器与存储 > 存储管理",
        ),
        SettingsSearchItem(
            id = "linux_storage_clean",
            title = "清理构建缓存与临时文件 (Cache Clean)",
            subtitle = "安全释放 Gradle 依赖缓存、临时日志与无用安装包",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.STORAGE_USAGE,
            icon = RuntimeIconName.Trash,
            keywords = listOf("clean", "cache", "trash", "清理", "缓存", "垃圾", "释放空间", "qingli"),
            badge = "清理",
            breadcrumb = "Linux 容器与存储 > 存储管理 > 缓存清理",
        ),
        SettingsSearchItem(
            id = "linux_storage_mounts",
            title = "存储挂载与共享",
            subtitle = "PRoot 宿主存储映射 (-b /sdcard)，访问手机本地文件与下载目录",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.STORAGE_MOUNTS,
            icon = RuntimeIconName.SdCard,
            keywords = listOf("mount", "sdcard", "bind", "挂载", "共享", "存储映射", "相册", "下载", "guazai", "sdka"),
            breadcrumb = "Linux 容器与存储 > 存储挂载",
        ),
        SettingsSearchItem(
            id = "linux_storage_custom_mount",
            title = "添加自定义宿主目录挂载点",
            subtitle = "将指定 Android 目录精确挂载映射进 Linux 虚拟路径",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.STORAGE_MOUNTS,
            icon = RuntimeIconName.Plus,
            keywords = listOf("bind mount", "custom mount", "添加挂载", "自定义挂载", "tianjiaguazai"),
            breadcrumb = "Linux 容器与存储 > 存储挂载 > 新建挂载点",
        ),
        SettingsSearchItem(
            id = "linux_storage_readonly_toggle",
            title = "存储挂载只读模式 (Read-Only) 开关",
            subtitle = "将敏感目录设为只读挂载，防止沙箱命令误改或误删宿主数据",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.STORAGE_MOUNTS,
            icon = RuntimeIconName.Shield,
            keywords = listOf("readonly", "ro", "rw", "只读", "读写权限", "防误删", "zhidu"),
            breadcrumb = "Linux 容器与存储 > 存储挂载 > 权限控制",
        ),
        SettingsSearchItem(
            id = "linux_env_vars",
            title = "沙箱环境变量",
            subtitle = "为终端、Agent 和沙箱工具注入全局用户环境变量 (PATH, EXPORT)",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.ENV_VARS,
            icon = RuntimeIconName.Key,
            keywords = listOf("env", "environment", "export", "path", "环境变量", "变量", "huanjingbianliang"),
            breadcrumb = "Linux 容器与存储 > 环境变量",
        ),
        SettingsSearchItem(
            id = "linux_env_proxy",
            title = "网络代理环境变量 (HTTP_PROXY / HTTPS_PROXY)",
            subtitle = "为 apt、curl、git、pip 等命令行工具配置局域网代理",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.ENV_VARS,
            icon = RuntimeIconName.Network,
            keywords = listOf("http_proxy", "https_proxy", "proxy", "网络代理", "科学上网", "代理", "daili"),
            breadcrumb = "Linux 容器与存储 > 环境变量 > 网络代理",
        ),
        SettingsSearchItem(
            id = "linux_ssh",
            title = "SSH 远程访问服务",
            subtitle = "内置 OpenSSH 服务端、公钥认证与局域网终端远程接入",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.SSH_SETTINGS,
            icon = RuntimeIconName.Network,
            keywords = listOf("ssh", "remote", "terminal", "port 22", "远程", "公钥", "端口", "yuancheng"),
            breadcrumb = "Linux 容器与存储 > SSH 远程访问",
        ),
        SettingsSearchItem(
            id = "linux_ssh_port",
            title = "SSH 服务监听端口配置 (Port 22/2222)",
            subtitle = "自定义 SSH Server 监听端口，避免与宿主或其他服务冲突",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.SSH_SETTINGS,
            icon = RuntimeIconName.Tune,
            keywords = listOf("ssh port", "port", "端口", "2222", "22", "duankou"),
            breadcrumb = "Linux 容器与存储 > SSH 远程访问 > 端口配置",
        ),
        SettingsSearchItem(
            id = "linux_ssh_pubkey",
            title = "SSH 授权公钥 (authorized_keys) 导入",
            subtitle = "粘贴电脑的 id_rsa.pub 公钥，实现免密码极速 SSH 登录",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.SSH_SETTINGS,
            icon = RuntimeIconName.Key,
            keywords = listOf("authorized_keys", "public key", "公钥", "免密登录", "gongyao"),
            breadcrumb = "Linux 容器与存储 > SSH 远程访问 > 公钥认证",
        ),
        SettingsSearchItem(
            id = "linux_ftp",
            title = "FTP 远程文件访问",
            subtitle = "挂载 Linux 根目录 (/)，电脑 FileZilla 或资源管理器直连互传",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.FTP_SETTINGS,
            icon = RuntimeIconName.FolderOpen,
            keywords = listOf("ftp", "filezilla", "sftp", "文件传输", "互传", "远程文件", "wenjianchuanshu"),
            breadcrumb = "Linux 容器与存储 > FTP 远程文件",
        ),
        SettingsSearchItem(
            id = "linux_ftp_credentials",
            title = "FTP 端口与用户密码认证",
            subtitle = "自定义 FTP 监听端口与访问账号密码，保证局域网互传安全",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.FTP_SETTINGS,
            icon = RuntimeIconName.Key,
            keywords = listOf("ftp port", "password", "密码", "ftp账号", "mima"),
            breadcrumb = "Linux 容器与存储 > FTP 远程文件 > 认证安全",
        ),
        SettingsSearchItem(
            id = "linux_web_chat",
            title = "天玄智枢 Web 协作台",
            subtitle = "局域网内使用电脑浏览器直接访问天玄 Agent 与工作区 (PIN 验证)",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.WEB_CHAT,
            icon = RuntimeIconName.Globe,
            keywords = listOf("web", "browser", "pin", "局域网", "电脑协作", "网页端", "xiezuotai"),
            breadcrumb = "Linux 容器与存储 > Web 协作台",
        ),
        SettingsSearchItem(
            id = "linux_apps",
            title = "Android 应用管理",
            subtitle = "同步宿主系统/用户应用，查看冻结状态与后台联网限制",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.APP_MANAGEMENT,
            icon = RuntimeIconName.Package,
            keywords = listOf("app", "package", "freeze", "应用", "冻结", "包名", "yingyong"),
            breadcrumb = "Linux 容器与存储 > 应用管理",
        ),
        SettingsSearchItem(
            id = "linux_privilege_mode",
            title = "系统运行特权模式",
            subtitle = "PRoot 无根沙箱、Root 特权或 Shizuku 授权运行模式切换",
            category = SettingsSearchCategory.LINUX_ENV,
            target = SettingsSearchTarget.PRIVILEGE_MODE,
            icon = RuntimeIconName.Key,
            keywords = listOf("root", "shizuku", "proot", "privilege", "特权", "模式", "授权", "tequan"),
            breadcrumb = "Linux 容器与存储 > 运行特权模式",
        ),

        // ==================== 3. 外观、字号与终端定制 ====================
        SettingsSearchItem(
            id = "appearance_theme",
            title = "主题模式与色彩风格",
            subtitle = "切换浅色、曜石深色、跟随系统，支持 Material You 动态壁纸取色",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.THEME_MODE,
            icon = RuntimeIconName.Palette,
            keywords = listOf("theme", "dark", "light", "color", "主题", "浅色", "深色", "曜石", "色彩", "zhuti"),
            breadcrumb = "外观、字号与终端 > 主题色彩",
        ),
        SettingsSearchItem(
            id = "appearance_dynamic_color",
            title = "Material You 动态取色开关",
            subtitle = "根据系统壁纸自动抽取主色调与强调色，保持系统级设计一致",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.DYNAMIC_COLOR,
            icon = RuntimeIconName.Palette,
            keywords = listOf("material you", "monet", "动态取色", "壁纸取色", "quse"),
            breadcrumb = "外观、字号与终端 > 主题色彩 > 动态壁纸取色",
        ),
        SettingsSearchItem(
            id = "appearance_liquid_glass",
            title = "澄明液态玻璃动效",
            subtitle = "半透明毛玻璃折射与液态玻璃材质界面微光特效",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.LIQUID_GLASS,
            icon = RuntimeIconName.Sparkles,
            keywords = listOf("glass", "liquid", "blur", "液态玻璃", "毛玻璃", "磨砂", "透明", "澄明", "yetai"),
            badge = "特色",
            breadcrumb = "外观、字号与终端 > 液态玻璃",
        ),
        SettingsSearchItem(
            id = "appearance_font_scale",
            title = "应用字号与页面缩放",
            subtitle = "调节天玄全界面文本字号大小与排版比例 (0.8x ~ 1.3x)",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.FONT_SCALE,
            icon = RuntimeIconName.FontSize,
            keywords = listOf("font", "scale", "size", "字号", "字体大小", "缩放", "排版", "zihao"),
            breadcrumb = "外观、字号与终端 > 字号排版",
        ),
        SettingsSearchItem(
            id = "appearance_terminal",
            title = "终端定制 (字体/字号/配色/触感)",
            subtitle = "配置 Linux 终端字体大小、Monokai/Dracula 配色方案与按键震动",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.TERMINAL_SETTINGS,
            icon = RuntimeIconName.Terminal,
            keywords = listOf("terminal", "color scheme", "font", "vibrate", "终端字体", "终端配色", "震动", "配色", "zhongduan"),
            breadcrumb = "外观、字号与终端 > 终端定制",
        ),
        SettingsSearchItem(
            id = "appearance_terminal_fontsize",
            title = "终端字体大小精确微调 (10sp~24sp)",
            subtitle = "按像素级调节 PTY 命令行终端的字符大小与行高间距",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.TERMINAL_SETTINGS,
            icon = RuntimeIconName.FontSize,
            keywords = listOf("terminal font size", "终端字号", "字符大小", "sp", "zhongduanzihao"),
            breadcrumb = "外观、字号与终端 > 终端定制 > 字体大小",
        ),
        SettingsSearchItem(
            id = "appearance_terminal_colorscheme",
            title = "终端配色方案 (Monokai / Dracula / One Dark)",
            subtitle = "内置 Solarized、Dracula、Nord、Monokai 等经典黑客主题色彩",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.TERMINAL_SETTINGS,
            icon = RuntimeIconName.Palette,
            keywords = listOf("monokai", "dracula", "one dark", "solarized", "nord", "终端主题", "命令行颜色"),
            breadcrumb = "外观、字号与终端 > 终端定制 > 配色方案",
        ),
        SettingsSearchItem(
            id = "appearance_terminal_haptic",
            title = "终端软键盘按键触感震动反馈",
            subtitle = "终端输入按键时触发轻微线性马达触感震动反馈",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.TERMINAL_SETTINGS,
            icon = RuntimeIconName.Vibrate,
            keywords = listOf("vibrate", "haptic", "触感", "震动", "马达反馈", "zhendong"),
            breadcrumb = "外观、字号与终端 > 终端定制 > 触感反馈",
        ),
        SettingsSearchItem(
            id = "appearance_language",
            title = "界面语言 (Language)",
            subtitle = "切换应用语言（简体中文 / English / 跟随系统）",
            category = SettingsSearchCategory.APPEARANCE,
            target = SettingsSearchTarget.LANGUAGE_SETTINGS,
            icon = RuntimeIconName.Globe,
            keywords = listOf("language", "locale", "chinese", "english", "语言", "中文", "英文", "yuyan"),
            breadcrumb = "外观、字号与终端 > 界面语言",
        ),

        // ==================== 4. 系统保活与开发者诊断 ====================
        SettingsSearchItem(
            id = "system_battery",
            title = "后台运行与电池优化白名单",
            subtitle = "忽略电池优化，防止 Android 系统在后台休眠时杀死沙箱进程",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.BATTERY_OPTIMIZATION,
            icon = RuntimeIconName.Battery,
            keywords = listOf("battery", "background", "keep alive", "保活", "电池", "白名单", "后台", "baohuo", "dianchi"),
            badge = "重要",
            breadcrumb = "系统保活与开发者 > 电池优化白名单",
        ),
        SettingsSearchItem(
            id = "system_phantom",
            title = "幽灵进程限制 (Phantom Process)",
            subtitle = "检测 Android 12+ 32 进程上限限制，提供一键解除或 ADB 修复指令",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.PHANTOM_PROCESS,
            icon = RuntimeIconName.Bug,
            keywords = listOf("phantom", "process", "limit", "32", "幽灵进程", "进程限制", "android 12", "youling"),
            badge = "必看",
            breadcrumb = "系统保活与开发者 > 幽灵进程破解",
        ),
        SettingsSearchItem(
            id = "system_oem_autostart",
            title = "OEM 深度休眠防护 (MIUI/鸿蒙自启动)",
            subtitle = "针对小米神隐模式、华为自启动管理、OPPO/vivo 的保活配置引导",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.BATTERY_OPTIMIZATION,
            icon = RuntimeIconName.Shield,
            keywords = listOf("miui", "hyperos", "harmonyos", "autostart", "神隐模式", "自启动", "防休眠"),
            breadcrumb = "系统保活与开发者 > OEM 深度防护",
        ),
        SettingsSearchItem(
            id = "system_developer",
            title = "开发者选项与调试模式",
            subtitle = "PRoot 详细日志开关、调试面板与内部运行时状态监控",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.DEVELOPER_OPTIONS,
            icon = RuntimeIconName.Admin,
            keywords = listOf("developer", "debug", "logs", "开发者", "调试", "日志", "kaifazhe", "tiaoshi"),
            breadcrumb = "系统保活与开发者 > 开发者选项",
        ),
        SettingsSearchItem(
            id = "system_adb_logcat",
            title = "无线 ADB 与 Logcat 日志抓取",
            subtitle = "免 Root 通过局域网 Kadb 协议实时抓取系统与应用崩溃日志",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.ADB_LOGCAT,
            icon = RuntimeIconName.Logs,
            keywords = listOf("adb", "logcat", "crash", "wireless", "日志", "崩溃", "无线adb", "rizhi"),
            breadcrumb = "系统保活与开发者 > 无线 ADB 日志",
        ),
        SettingsSearchItem(
            id = "system_custom_iteration",
            title = "自定义迭代自愈",
            subtitle = "通过自然语言 Prompt 驱动 Agent 诊断沙箱问题并实施代码热修补",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.CUSTOM_ITERATION,
            icon = RuntimeIconName.Sparkles,
            keywords = listOf("iteration", "healing", "prompt", "迭代", "自愈", "修复", "diedai"),
            breadcrumb = "系统保活与开发者 > 自定义迭代自愈",
        ),
        SettingsSearchItem(
            id = "system_permission_guide",
            title = "权限配置检查向导",
            subtitle = "一键检查存储权限、通知权限、电池白名单与自启动权限",
            category = SettingsSearchCategory.SYSTEM_DEV,
            target = SettingsSearchTarget.PERMISSION_GUIDE,
            icon = RuntimeIconName.Shield,
            keywords = listOf("permission", "guide", "storage", "notification", "权限", "存储", "通知", "自启动", "quanxian"),
            breadcrumb = "系统保活与开发者 > 权限检查向导",
        ),

        // ==================== 5. 智坊工作区与构建环境 ====================
        SettingsSearchItem(
            id = "workshop_settings",
            title = "智坊工程与构建配置",
            subtitle = "管理工作区项目构建命令、生命周期脚本与自动化打包配置",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_SETTINGS,
            icon = RuntimeIconName.Workspace,
            keywords = listOf("workshop", "build", "script", "智坊", "构建", "脚本", "工程", "gongfang", "goujian"),
            breadcrumb = "智坊与离线构建 > 工程构建配置",
        ),
        SettingsSearchItem(
            id = "workshop_env",
            title = "智坊离线环境 (Android SDK/NDK)",
            subtitle = "配置沙箱内 Android SDK、NDK、Gradle、CMake 与 JDK 离线工具链",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_ENVIRONMENT,
            icon = RuntimeIconName.Android,
            keywords = listOf("sdk", "ndk", "gradle", "cmake", "jdk", "离线构建", "android sdk", "huanjing"),
            badge = "离线SDK",
            breadcrumb = "智坊与离线构建 > 离线开发环境",
        ),
        SettingsSearchItem(
            id = "workshop_ndk_path",
            title = "Android NDK 工具链路径配置",
            subtitle = "指定 C/C++ 交叉编译 NDK 路径，支持 CMake 与移动端原生构建",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_ENVIRONMENT,
            icon = RuntimeIconName.Code,
            keywords = listOf("ndk", "ndkpath", "c++", "cmake", "交叉编译", "ndk路径"),
            breadcrumb = "智坊与离线构建 > 离线开发环境 > NDK",
        ),
        SettingsSearchItem(
            id = "workshop_signing",
            title = "APK 签名密钥与证书",
            subtitle = "配置 Android 签名密钥库 (Keystore)、别名与签名打包证书",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_SIGNING,
            icon = RuntimeIconName.Key,
            keywords = listOf("signing", "keystore", "apk", "cert", "签名", "证书", "密钥库", "qianming"),
            breadcrumb = "智坊与离线构建 > APK 签名管理",
        ),
        SettingsSearchItem(
            id = "workshop_signing_alias",
            title = "Keystore 密钥别名与密码配置",
            subtitle = "管理发布版 (Release) 与调试版 (Debug) 的 Key Alias 与密码",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_SIGNING,
            icon = RuntimeIconName.Key,
            keywords = listOf("alias", "keypass", "storepass", "别名", "密钥密码", "bieming"),
            breadcrumb = "智坊与离线构建 > APK 签名管理 > 证书别名",
        ),
        SettingsSearchItem(
            id = "workshop_script_init",
            title = "Init 项目初始化生命周期脚本",
            subtitle = "配置工程创建或打开时自动执行的依赖下载与准备命令",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_SETTINGS,
            icon = RuntimeIconName.Edit,
            keywords = listOf("init script", "lifecycle", "初始化脚本", "chushihua"),
            breadcrumb = "智坊与离线构建 > 构建脚本 > Init",
        ),
        SettingsSearchItem(
            id = "workshop_script_build",
            title = "Build 项目编译打包脚本",
            subtitle = "配置 Gradle assembleRelease、Flutter build 等打包指令",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKSHOP_SETTINGS,
            icon = RuntimeIconName.Play,
            keywords = listOf("build script", "assemble", "编译脚本", "打包指令", "bianyi"),
            breadcrumb = "智坊与离线构建 > 构建脚本 > Build",
        ),
        SettingsSearchItem(
            id = "workshop_workflows",
            title = "自动化工作流 (Workflow)",
            subtitle = "基于 DAG 的自动化任务流程编排、步骤审批与无人值守流水线",
            category = SettingsSearchCategory.WORKSHOP,
            target = SettingsSearchTarget.WORKFLOWS,
            icon = RuntimeIconName.Speed,
            keywords = listOf("workflow", "dag", "pipeline", "工作流", "自动化", "流水线", "gongzuoliu"),
            breadcrumb = "智坊与离线构建 > 自动化工作流",
        ),

        // ==================== 6. 天玄核心功能直达 ====================
        SettingsSearchItem(
            id = "nav_home",
            title = "天玄主画卷 (开辟画布)",
            subtitle = "天玄主控仪表盘、沙箱快捷启动与状态概览",
            category = SettingsSearchCategory.CORE_FEATURE,
            target = SettingsSearchTarget.NAV_HOME,
            icon = RuntimeIconName.NavDashboard,
            keywords = listOf("home", "dashboard", "主页", "画布", "天玄", "zhuye"),
            breadcrumb = "天玄核心直达 > 主画卷",
        ),
        SettingsSearchItem(
            id = "nav_agent_chat",
            title = "智枢 AI 结对编程",
            subtitle = "智能体对话交互主界面、结对写代码与多轮任务协作",
            category = SettingsSearchCategory.CORE_FEATURE,
            target = SettingsSearchTarget.NAV_AGENT_CHAT,
            icon = RuntimeIconName.NavMessage,
            keywords = listOf("chat", "agent", "ai", "智枢", "对话", "结对", "duihua"),
            breadcrumb = "天玄核心直达 > 智枢 AI 会话",
        ),
        SettingsSearchItem(
            id = "nav_workspace",
            title = "智坊代码工作区",
            subtitle = "项目文件浏览、内嵌代码编辑器与工程管理器",
            category = SettingsSearchCategory.CORE_FEATURE,
            target = SettingsSearchTarget.NAV_WORKSPACE,
            icon = RuntimeIconName.NavRepository,
            keywords = listOf("workspace", "files", "project", "工作区", "文件", "代码", "gongzuoqu"),
            breadcrumb = "天玄核心直达 > 智坊工作区",
        ),
        SettingsSearchItem(
            id = "nav_terminal",
            title = "内置交互式终端 (PTY)",
            subtitle = "全功能 Linux PTY 原生终端命令行，支持沙箱命令执行与快捷键",
            category = SettingsSearchCategory.CORE_FEATURE,
            target = SettingsSearchTarget.NAV_TERMINAL,
            icon = RuntimeIconName.Terminal,
            keywords = listOf("terminal", "pty", "bash", "shell", "终端", "命令行", "zhongduan"),
            badge = "直达",
            breadcrumb = "天玄核心直达 > 原生 PTY 终端",
        ),
        SettingsSearchItem(
            id = "nav_browser",
            title = "内置沙箱浏览器",
            subtitle = "支持 CDP 调试、网络拦截 Hook 与 Agent 联动的专用浏览器",
            category = SettingsSearchCategory.CORE_FEATURE,
            target = SettingsSearchTarget.NAV_BROWSER,
            icon = RuntimeIconName.Globe,
            keywords = listOf("browser", "cdp", "webview", "浏览器", "网页", "liulanqi"),
            breadcrumb = "天玄核心直达 > 内置浏览器",
        ),

        // ==================== 7. 关于与官方社区 ====================
        SettingsSearchItem(
            id = "about_community",
            title = "关于天玄与官方社区",
            subtitle = "检查版本更新、查看开源协议、GitHub 仓库与官方 QQ 交流群",
            category = SettingsSearchCategory.ABOUT,
            target = SettingsSearchTarget.ABOUT_COMMUNITY,
            icon = RuntimeIconName.Community,
            keywords = listOf("about", "version", "github", "qq", "community", "关于", "版本", "更新", "开源", "交流群", "guanyu"),
            breadcrumb = "关于与官方社区 > 关于天玄",
        ),
        SettingsSearchItem(
            id = "about_changelog",
            title = "版本更新日志与升级检测",
            subtitle = "查看各版本演进说明、Release 更新日志与新特性介绍",
            category = SettingsSearchCategory.ABOUT,
            target = SettingsSearchTarget.ABOUT_COMMUNITY,
            icon = RuntimeIconName.Update,
            keywords = listOf("update", "changelog", "更新", "新版本", "日志", "gengxin"),
            breadcrumb = "关于与官方社区 > 版本更新",
        ),
        SettingsSearchItem(
            id = "about_github",
            title = "GitHub 开源仓库与源码",
            subtitle = "天玄开源项目地址、提交 Issue 反馈与代码贡献",
            category = SettingsSearchCategory.ABOUT,
            target = SettingsSearchTarget.ABOUT_COMMUNITY,
            icon = RuntimeIconName.Github,
            keywords = listOf("github", "open source", "issue", "开源", "仓库", "kaiyuan"),
            breadcrumb = "关于与官方社区 > GitHub 仓库",
        ),
        SettingsSearchItem(
            id = "about_sponsor",
            title = "赞助天玄开发",
            subtitle = "支持天玄开源项目持续迭代与移动端 Linux 沙箱生态演进",
            category = SettingsSearchCategory.ABOUT,
            target = SettingsSearchTarget.ABOUT_SPONSOR,
            icon = RuntimeIconName.Sponsor,
            keywords = listOf("sponsor", "donate", "赞助", "捐赠", "支持", "zanzhu"),
            breadcrumb = "关于与官方社区 > 赞助开发者",
        ),
    )

    /**
     * 多维加权匹配算法：
     * - 标题完全匹配：100分
     * - 标题前缀匹配：80分
     * - 标题包含匹配：60分
     * - 关键词包含匹配：40分
     * - 描述包含匹配：25分
     * - 面包屑路径匹配：20分
     * - 分类名称包含匹配：10分
     */
    fun search(query: String): List<SettingsSearchItem> {
        val trimmed = query.trim().lowercase()
        if (trimmed.isEmpty()) return allItems

        // 拆分子词（支持空格分割的多词搜索）
        val subQueries = trimmed.split("\\s+".toRegex()).filter { it.isNotEmpty() }

        return allItems
            .mapNotNull { item ->
                var score = 0
                val titleLower = item.title.lowercase()
                val subtitleLower = item.subtitle.lowercase()
                val categoryLower = item.category.label.lowercase()
                val breadcrumbLower = item.breadcrumb?.lowercase().orEmpty()

                // 优先全词匹配
                if (titleLower == trimmed) {
                    score += 100
                } else if (titleLower.startsWith(trimmed)) {
                    score += 80
                } else if (titleLower.contains(trimmed)) {
                    score += 60
                }

                if (item.keywords.any { it.lowercase().contains(trimmed) }) {
                    score += 40
                }

                if (subtitleLower.contains(trimmed)) {
                    score += 25
                }

                if (breadcrumbLower.contains(trimmed)) {
                    score += 20
                }

                if (categoryLower.contains(trimmed)) {
                    score += 10
                }

                // 如果多词搜索，检查各子词的命中情况
                if (subQueries.size > 1) {
                    val allMatched = subQueries.all { sub ->
                        titleLower.contains(sub) ||
                        subtitleLower.contains(sub) ||
                        breadcrumbLower.contains(sub) ||
                        item.keywords.any { it.lowercase().contains(sub) }
                    }
                    if (allMatched) {
                        score += 50
                    }
                }

                if (score > 0) item to score else null
            }
            .sortedByDescending { it.second }
            .map { it.first }
    }
}
